# Generated by Django 3.0.7 on 2020-06-28 06:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
        ('webs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posts',
            name='user_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posts',
            name='web_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webs.Webs', validators=[django.core.validators.URLValidator], verbose_name='Enter the URL of the website'),
        ),
    ]
