# Generated by Django 3.0.7 on 2020-06-28 06:37

from django.db import migrations, models
import webs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webs',
            fields=[
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False, validators=[webs.models.validate_url])),
                ('name', models.CharField(max_length=255, unique=True)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
    ]
